# Generated by Django 6.0.6 on 2026-07-04 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureupload',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='generatednote',
            name='diagram_code',
        ),
        migrations.AddField(
            model_name='generatednote',
            name='ai_model_used',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='concept_graph_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='key_concepts_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='mermaid_diagram',
            field=models.TextField(blank=True, help_text='Mermaid.js diagram code', null=True),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='processing_time_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='quiz_questions_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='skeleton_outline_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='summary_text',
            field=models.TextField(blank=True, help_text='Short 2-3 sentence summary'),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='topic_relationships_json',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='generatednote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lectureupload',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lectureupload',
            name='file_type',
            field=models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], default='audio', max_length=10),
        ),
        migrations.AddField(
            model_name='lectureupload',
            name='processing_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='generatednote',
            name='summary_markdown',
            field=models.TextField(help_text='Full structured Markdown notes from Gemini'),
        ),
        migrations.AlterField(
            model_name='lectureupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL),
        ),
    ]
